import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const calls=[];
const context = {URL,crypto,chrome:{runtime:{sendNativeMessage:async (host,message)=>{calls.push({host,message});return {protocol:1,request_id:message.request_id,status:'delivered'};}}}};
vm.createContext(context);
vm.runInContext(readFileSync(new URL('../shared/core.js',import.meta.url),'utf8'),context);
const c = context.YTDCompanion;
for (const url of ['chrome://settings','edge://extensions','about:addons','file:///secret','javascript:alert(1)','http://localhost/a','http://127.0.0.1/a','http://192.168.1.1/','https://user:secret@example.org/']) assert.equal(c.validUrl(url),false,url);
assert.equal(c.validUrl('https://example.org/video'),true);
assert.equal(c.validUrl('http://[fd00::1]/'),false);
assert.equal(c.validUrl('https://[2606:4700:4700::1111]/'),true);
assert.equal(c.contextUrl({menuItemId:'send-link',linkUrl:'https://target.example/a',pageUrl:'https://page.example/'},{url:'https://tab.example/'}),'https://target.example/a');
await c.native('send_url','file:///secret');assert.equal(calls.length,0);
await c.native('send_url','https://example.org/$(calc)');
assert.deepEqual(Object.keys(calls[0].message).sort(),['action','protocol','request_id','url']);
assert.equal(calls[0].message.url,'https://example.org/$(calc)');
assert.equal(c.statusKey({status:'delivered'},true),'sent');
assert.equal(c.statusKey({status:'accepted',app_running:false}),'ready');
assert.equal(c.statusKey({status:'host_unavailable'}),'host_unavailable');
assert.equal(c.statusKey({status:'app_launch_failed'}),'app_launch_failed');
console.log('EXTENSION CORE: 20 assertions passed; link target wins; URL-only; no download request.');
let installed,clicked;const menus=[],badges=[];
context.chrome.runtime.onInstalled={addListener:f=>installed=f};
context.chrome.contextMenus={removeAll:async()=>{},create:m=>menus.push(m),onClicked:{addListener:f=>clicked=f}};
context.chrome.i18n={getMessage:k=>k};
context.chrome.action={setBadgeText:async m=>badges.push(m.text),setBadgeBackgroundColor:async()=>{},setTitle:async()=>{}};
vm.runInContext(readFileSync(new URL('../shared/background.js',import.meta.url),'utf8'),context);
await installed();assert.equal(menus.length,2);
await clicked({menuItemId:'send-link',linkUrl:'https://target.example/video',pageUrl:'https://page.example/'},{url:'https://tab.example/'});
assert.equal(calls.at(-1).message.url,'https://target.example/video');
assert.equal(badges.at(-1),'✓');
console.log('EXTENSION BACKGROUND: install menus + link dispatch + native receipt passed.');
