"""Generate first-party localized companion assets (no signing key is saved)."""
from pathlib import Path
import base64
import hashlib
import json
import shutil
import re

ROOT = Path(__file__).resolve().parents[1]
KEYS = 'title description install test repair remove folder help identity not_configured configured connected repair_needed bridge_missing registration_conflict unauthorized_extension operation_failed folder_opened test_in_browser install_help firefox_help privacy current_page send choose_desktop checking ready sent invalid_url app_launch_failed protocol_mismatch busy host_unavailable send_page send_link sending name'.split()
ROWS = {
'zh-CN': '浏览器扩展|从浏览器发送链接，在桌面应用中解析并选择画质。|配置连接|测试连接|修复连接|移除连接|打开扩展文件夹|安装帮助|扩展 ID（商店版本可重新关联）|尚未配置|本地桥接已配置，等待浏览器连接|已连接（最近五分钟）|需要修复连接|未找到 YTDownloaderBridge.exe，请使用完整便携包。|现有注册项不属于本应用，未覆盖。|扩展 ID 无效，请检查安装页面。|操作失败，请检查应用目录和当前用户权限。|已打开扩展文件夹|本地连接有效；请在浏览器中打开扩展并点击发送以验证。|先配置对应浏览器，打开扩展文件夹。在 chrome://extensions 或 edge://extensions 开启开发者模式，选择“加载解压缩的扩展”，选中对应文件夹。移动便携包后点击修复连接。|Firefox：在 about:debugging 的“此 Firefox”中临时载入 manifest.json。临时安装重启后消失；持久安装需要 Mozilla 签名，此开发版尚未签名。|仅发送你主动选择的网页链接。扩展不读取 Cookie，也不自动下载；登录来源沿用桌面配置。|当前网页|发送到 YTDownloader|在桌面应用中选择画质并下载|正在检查连接…|桥接已就绪，发送时将启动应用|已发送至 YTDownloader，请在桌面应用中查看解析结果。|当前页面链接无法发送。|无法启动 YTDownloader，请检查应用位置。|连接协议不兼容，请更新扩展和应用。|解析队列已满，请稍后重试。|未检测到本地连接，请先在工具箱配置浏览器扩展。|发送当前网页到 YTDownloader|发送此链接到 YTDownloader|正在发送…|发送到桌面应用',
'zh-TW': '瀏覽器擴充功能|從瀏覽器傳送連結，在桌面應用程式中解析並選擇畫質。|設定連線|測試連線|修復連線|移除連線|開啟擴充功能資料夾|安裝說明|擴充功能 ID（商店版本可重新關聯）|尚未設定|本機橋接已設定，等待瀏覽器連線|已連線（最近五分鐘）|需要修復連線|找不到 YTDownloaderBridge.exe，請使用完整可攜套件。|現有登錄項目不屬於此應用程式，未覆寫。|擴充功能 ID 無效，請檢查安裝頁面。|操作失敗，請檢查應用程式路徑與使用者權限。|已開啟擴充功能資料夾|本機連線有效；請在瀏覽器開啟擴充功能並傳送連結以驗證。|先設定瀏覽器並開啟擴充功能資料夾。在 chrome://extensions 或 edge://extensions 開啟開發人員模式，載入解壓縮的擴充功能資料夾。移動可攜套件後請修復連線。|Firefox：在 about:debugging 的「此 Firefox」暫時載入 manifest.json。重啟後會移除；永久安裝需要 Mozilla 簽章，此開發版尚未簽章。|僅傳送主動選擇的網頁連結。不讀取 Cookie，也不自動下載；沿用桌面登入設定。|目前網頁|傳送至 YTDownloader|在桌面應用程式中選擇畫質並下載|正在檢查連線…|橋接已就緒，傳送時將啟動應用程式|已傳送至 YTDownloader，請在桌面查看解析結果。|無法傳送此網頁連結。|無法啟動 YTDownloader，請檢查位置。|連線協定不相容，請更新擴充功能與應用程式。|解析佇列已滿，請稍後再試。|找不到本機連線，請先在工具箱設定擴充功能。|傳送目前網頁至 YTDownloader|傳送此連結至 YTDownloader|正在傳送…|傳送至桌面應用程式',
'en': 'Browser extension|Send a link from your browser, then choose quality in the desktop app.|Configure connection|Test connection|Repair connection|Remove connection|Open extension folder|Installation help|Extension ID (reassociate store builds here)|Not configured|Local bridge configured; waiting for browser connection|Connected within the last five minutes|Connection needs repair|YTDownloaderBridge.exe is missing. Use the complete portable package.|An existing registration belongs to another installation; it was preserved.|Invalid extension ID. Check the browser extension page.|Operation failed. Check the application location and user permissions.|Extension folder opened|Local connection is valid. Open the browser extension and send a link to verify it.|Configure the browser and open its extension folder. Enable developer mode at chrome://extensions or edge://extensions, then load the unpacked folder. Repair the connection after moving the portable app.|Firefox: temporarily load manifest.json at about:debugging → This Firefox. Temporary installs disappear after restart. Persistent installs require Mozilla signing; this development build is unsigned.|Only links you explicitly send are transferred. No Cookie access or automatic downloads. Desktop login sources remain unchanged.|Current page|Send to YTDownloader|Choose quality and download in the desktop app|Checking connection…|Bridge ready; sending will launch the app|Sent to YTDownloader. Check the desktop app for parsing results.|This page link cannot be sent.|Cannot start YTDownloader. Check its location.|Incompatible protocol. Update the extension and app.|Parse queue is full. Try again shortly.|Local connection unavailable. Configure the extension in Toolbox first.|Send current page to YTDownloader|Send this link to YTDownloader|Sending…|Send to the desktop app',
'ja': 'ブラウザー拡張機能|ブラウザーからリンクを送り、アプリで解析して画質を選択します。|接続を設定|接続をテスト|接続を修復|接続を解除|拡張機能フォルダーを開く|インストール案内|拡張機能 ID（ストア版の再関連付け）|未設定|ローカル接続設定済み・ブラウザーの接続待ち|接続済み（過去5分以内）|接続の修復が必要|YTDownloaderBridge.exe がありません。完全なポータブル版を使用してください。|別のインストールの登録を保持しました。|拡張機能 ID が無効です。ブラウザーの管理画面を確認してください。|操作に失敗しました。アプリの場所と権限を確認してください。|フォルダーを開きました|ローカル接続は有効です。拡張機能からリンクを送って確認してください。|設定後、フォルダーを開きます。chrome://extensions または edge://extensions で開発者モードを有効にしてフォルダーを読み込みます。アプリ移動後は接続を修復してください。|Firefox：about:debugging の「この Firefox」で manifest.json を一時読み込みします。再起動で削除されます。永続インストールには Mozilla の署名が必要で、この開発版は未署名です。|明示的に送ったリンクのみ転送します。Cookie の読み取りや自動ダウンロードは行わず、アプリのログイン設定を使います。|現在のページ|YTDownloader に送る|アプリで画質を選択してダウンロード|接続を確認中…|接続準備完了・送信時にアプリを起動|YTDownloader に送信しました。解析結果はアプリで確認してください。|このページのリンクは送信できません。|アプリを起動できません。場所を確認してください。|プロトコルが非互換です。拡張機能とアプリを更新してください。|解析待ちがいっぱいです。後で再試行してください。|ローカル接続がありません。ツールボックスで設定してください。|現在のページを YTDownloader に送る|このリンクを YTDownloader に送る|送信中…|デスクトップアプリへ送信',
'ko': '브라우저 확장|브라우저에서 링크를 보내고 앱에서 분석하여 화질을 선택하세요.|연결 설정|연결 테스트|연결 복구|연결 제거|확장 폴더 열기|설치 도움말|확장 ID (스토어 버전 재연결)|설정되지 않음|로컬 연결 설정됨; 브라우저 연결 대기 중|연결됨 (최근 5분 이내)|연결 복구 필요|YTDownloaderBridge.exe가 없습니다. 전체 휴대용 패키지를 사용하세요.|다른 설치의 등록을 유지했습니다.|확장 ID가 잘못되었습니다. 브라우저 관리 페이지를 확인하세요.|작업 실패. 앱 위치와 사용자 권한을 확인하세요.|확장 폴더를 열었습니다|로컬 연결이 유효합니다. 확장을 열고 링크를 보내 확인하세요.|설정 후 확장 폴더를 여세요. chrome://extensions 또는 edge://extensions에서 개발자 모드를 켜고 압축 해제된 폴더를 로드하세요. 앱 이동 후 연결을 복구하세요.|Firefox: about:debugging의 이 Firefox에서 manifest.json을 임시 로드하세요. 재시작하면 제거됩니다. 영구 설치에는 Mozilla 서명이 필요하며 이 개발 버전은 서명되지 않았습니다.|직접 보낸 링크만 전송합니다. Cookie를 읽거나 자동 다운로드하지 않습니다. 앱의 로그인 설정을 사용합니다.|현재 페이지|YTDownloader로 보내기|앱에서 화질을 선택하고 다운로드하세요|연결 확인 중…|연결 준비 완료; 전송 시 앱 시작|YTDownloader로 전송했습니다. 앱에서 분석 결과를 확인하세요.|이 페이지 링크를 보낼 수 없습니다.|앱을 시작할 수 없습니다. 위치를 확인하세요.|호환되지 않는 프로토콜입니다. 확장과 앱을 업데이트하세요.|분석 대기열이 가득 찼습니다. 잠시 후 다시 시도하세요.|로컬 연결이 없습니다. 도구 상자에서 먼저 설정하세요.|현재 페이지를 YTDownloader로 보내기|이 링크를 YTDownloader로 보내기|전송 중…|데스크톱 앱으로 보내기',
'ru': 'Расширение браузера|Отправьте ссылку из браузера и выберите качество в приложении.|Настроить подключение|Проверить подключение|Восстановить подключение|Удалить подключение|Открыть папку расширения|Помощь с установкой|ID расширения (повторная привязка версии из магазина)|Не настроено|Локальный мост настроен; ожидается браузер|Подключено в течение последних пяти минут|Требуется восстановление|Нет YTDownloaderBridge.exe. Используйте полный переносной пакет.|Регистрация другой установки сохранена без изменений.|Неверный ID расширения. Проверьте страницу расширений.|Операция не выполнена. Проверьте расположение и права доступа.|Папка расширения открыта|Локальное подключение исправно. Откройте расширение и отправьте ссылку для проверки.|Настройте браузер и откройте папку. Включите режим разработчика в chrome://extensions или edge://extensions и загрузите распакованную папку. После переноса приложения восстановите подключение.|Firefox: временно загрузите manifest.json в about:debugging → Этот Firefox. После перезапуска установка исчезнет. Постоянная установка требует подписи Mozilla; эта сборка не подписана.|Передаются только явно отправленные ссылки. Нет доступа к Cookie и автоматических загрузок. Источники входа задаются в приложении.|Текущая страница|Отправить в YTDownloader|Выберите качество и загрузите в приложении|Проверка подключения…|Мост готов; отправка запустит приложение|Отправлено в YTDownloader. Результат анализа доступен в приложении.|Нельзя отправить ссылку этой страницы.|Не удалось запустить приложение. Проверьте расположение.|Несовместимый протокол. Обновите расширение и приложение.|Очередь анализа заполнена. Повторите позже.|Нет локального подключения. Настройте расширение в инструментах.|Отправить текущую страницу в YTDownloader|Отправить эту ссылку в YTDownloader|Отправка…|Отправить в приложение',
'es': 'Extensión del navegador|Envía un enlace y elige la calidad en la aplicación de escritorio.|Configurar conexión|Probar conexión|Reparar conexión|Eliminar conexión|Abrir carpeta de extensión|Ayuda de instalación|ID de extensión (reasociar versión de tienda)|Sin configurar|Puente local configurado; esperando al navegador|Conectado en los últimos cinco minutos|La conexión necesita reparación|Falta YTDownloaderBridge.exe. Usa el paquete portátil completo.|Se conservó el registro de otra instalación.|ID de extensión no válido. Revisa la página de extensiones.|Error de operación. Revisa la ubicación y los permisos.|Carpeta de extensión abierta|La conexión local es válida. Abre la extensión y envía un enlace para verificarla.|Configura el navegador y abre la carpeta. Activa el modo de desarrollador en chrome://extensions o edge://extensions y carga la carpeta descomprimida. Repara tras mover la aplicación.|Firefox: carga temporalmente manifest.json en about:debugging → Este Firefox. Se elimina al reiniciar. La instalación permanente requiere firma de Mozilla; esta versión no está firmada.|Solo se transfieren enlaces enviados explícitamente. Sin acceso a Cookie ni descargas automáticas. Se usa la configuración de acceso del escritorio.|Página actual|Enviar a YTDownloader|Elige la calidad y descarga en la aplicación|Comprobando conexión…|Puente listo; el envío iniciará la aplicación|Enviado a YTDownloader. Consulta el resultado en la aplicación.|No se puede enviar el enlace de esta página.|No se puede iniciar la aplicación. Revisa su ubicación.|Protocolo incompatible. Actualiza la extensión y la aplicación.|La cola de análisis está llena. Inténtalo más tarde.|Conexión local no disponible. Configura la extensión en Herramientas.|Enviar página actual a YTDownloader|Enviar este enlace a YTDownloader|Enviando…|Enviar a la aplicación',
'pt': 'Extensão do navegador|Envie um link e escolha a qualidade no aplicativo de desktop.|Configurar conexão|Testar conexão|Reparar conexão|Remover conexão|Abrir pasta da extensão|Ajuda de instalação|ID da extensão (reassociar versão da loja)|Não configurado|Ponte local configurada; aguardando o navegador|Conectado nos últimos cinco minutos|A conexão precisa de reparo|YTDownloaderBridge.exe ausente. Use o pacote portátil completo.|O registro de outra instalação foi preservado.|ID de extensão inválido. Confira a página de extensões.|Falha na operação. Confira o local e as permissões.|Pasta da extensão aberta|A conexão local é válida. Abra a extensão e envie um link para verificar.|Configure o navegador e abra a pasta. Ative o modo de desenvolvedor em chrome://extensions ou edge://extensions e carregue a pasta descompactada. Repare após mover o aplicativo.|Firefox: carregue temporariamente manifest.json em about:debugging → Este Firefox. A instalação desaparece ao reiniciar. A instalação permanente exige assinatura Mozilla; esta versão não está assinada.|Somente links enviados explicitamente são transferidos. Sem acesso a Cookie ou downloads automáticos. Usa as fontes de login do desktop.|Página atual|Enviar para YTDownloader|Escolha a qualidade e baixe no aplicativo|Verificando conexão…|Ponte pronta; o envio iniciará o aplicativo|Enviado para YTDownloader. Confira o resultado no aplicativo.|Não é possível enviar o link desta página.|Não foi possível iniciar o aplicativo. Confira o local.|Protocolo incompatível. Atualize a extensão e o aplicativo.|A fila de análise está cheia. Tente novamente em breve.|Conexão local indisponível. Configure a extensão nas Ferramentas.|Enviar página atual para YTDownloader|Enviar este link para YTDownloader|Enviando…|Enviar para o aplicativo',
'vi': 'Tiện ích trình duyệt|Gửi liên kết rồi chọn chất lượng trong ứng dụng máy tính.|Thiết lập kết nối|Kiểm tra kết nối|Sửa kết nối|Gỡ kết nối|Mở thư mục tiện ích|Hướng dẫn cài đặt|ID tiện ích (liên kết lại bản cửa hàng)|Chưa thiết lập|Cầu nối đã thiết lập; đang chờ trình duyệt|Đã kết nối trong năm phút qua|Cần sửa kết nối|Thiếu YTDownloaderBridge.exe. Dùng gói di động đầy đủ.|Đã giữ nguyên đăng ký của bản cài khác.|ID tiện ích không hợp lệ. Kiểm tra trang tiện ích.|Thao tác thất bại. Kiểm tra vị trí và quyền truy cập.|Đã mở thư mục tiện ích|Kết nối cục bộ hợp lệ. Mở tiện ích và gửi liên kết để kiểm tra.|Thiết lập trình duyệt và mở thư mục. Bật chế độ nhà phát triển tại chrome://extensions hoặc edge://extensions rồi tải thư mục đã giải nén. Sửa kết nối sau khi di chuyển ứng dụng.|Firefox: tải tạm manifest.json tại about:debugging → Firefox này. Tiện ích bị gỡ khi khởi động lại. Cài lâu dài cần chữ ký Mozilla; bản này chưa được ký.|Chỉ truyền liên kết bạn chủ động gửi. Không đọc Cookie hay tự tải xuống. Dùng nguồn đăng nhập đã chọn trong ứng dụng.|Trang hiện tại|Gửi tới YTDownloader|Chọn chất lượng và tải trong ứng dụng|Đang kiểm tra kết nối…|Cầu nối sẵn sàng; gửi sẽ mở ứng dụng|Đã gửi tới YTDownloader. Xem kết quả phân tích trong ứng dụng.|Không thể gửi liên kết trang này.|Không thể mở ứng dụng. Kiểm tra vị trí.|Giao thức không tương thích. Cập nhật tiện ích và ứng dụng.|Hàng đợi phân tích đầy. Thử lại sau.|Không có kết nối cục bộ. Thiết lập tiện ích trong Hộp công cụ.|Gửi trang hiện tại tới YTDownloader|Gửi liên kết này tới YTDownloader|Đang gửi…|Gửi tới ứng dụng máy tính',
'th': 'ส่วนขยายเบราว์เซอร์|ส่งลิงก์แล้วเลือกคุณภาพในแอปเดสก์ท็อป|ตั้งค่าการเชื่อมต่อ|ทดสอบการเชื่อมต่อ|ซ่อมการเชื่อมต่อ|ลบการเชื่อมต่อ|เปิดโฟลเดอร์ส่วนขยาย|วิธีติดตั้ง|ID ส่วนขยาย (เชื่อมรุ่นจากร้านค้าใหม่)|ยังไม่ได้ตั้งค่า|ตั้งค่าบริดจ์แล้ว รอเบราว์เซอร์เชื่อมต่อ|เชื่อมต่อในห้านาทีที่ผ่านมา|ต้องซ่อมการเชื่อมต่อ|ไม่พบ YTDownloaderBridge.exe โปรดใช้แพ็กเกจแบบพกพาครบชุด|เก็บการลงทะเบียนของการติดตั้งอื่นไว้แล้ว|ID ส่วนขยายไม่ถูกต้อง ตรวจสอบหน้าส่วนขยาย|ดำเนินการไม่สำเร็จ ตรวจสอบตำแหน่งและสิทธิ์|เปิดโฟลเดอร์ส่วนขยายแล้ว|การเชื่อมต่อภายในใช้งานได้ เปิดส่วนขยายและส่งลิงก์เพื่อยืนยัน|ตั้งค่าเบราว์เซอร์และเปิดโฟลเดอร์ เปิดโหมดนักพัฒนาที่ chrome://extensions หรือ edge://extensions แล้วโหลดโฟลเดอร์ที่แตกไฟล์ ซ่อมการเชื่อมต่อหลังย้ายแอป|Firefox: โหลด manifest.json ชั่วคราวที่ about:debugging → Firefox นี้ การติดตั้งหายไปเมื่อเปิดใหม่ การติดตั้งถาวรต้องใช้ลายเซ็น Mozilla รุ่นนี้ยังไม่ได้ลงนาม|ส่งเฉพาะลิงก์ที่คุณเลือกเอง ไม่อ่าน Cookie หรือดาวน์โหลดอัตโนมัติ ใช้แหล่งเข้าสู่ระบบของแอป|หน้าปัจจุบัน|ส่งไปยัง YTDownloader|เลือกคุณภาพและดาวน์โหลดในแอป|กำลังตรวจสอบการเชื่อมต่อ…|บริดจ์พร้อม ส่งแล้วจะเปิดแอป|ส่งไปยัง YTDownloader แล้ว ดูผลการวิเคราะห์ในแอป|ไม่สามารถส่งลิงก์หน้านี้|เปิดแอปไม่ได้ โปรดตรวจสอบตำแหน่ง|โปรโตคอลไม่เข้ากัน อัปเดตส่วนขยายและแอป|คิววิเคราะห์เต็ม โปรดลองอีกครั้งภายหลัง|ไม่พบการเชื่อมต่อภายใน ตั้งค่าส่วนขยายในกล่องเครื่องมือก่อน|ส่งหน้าปัจจุบันไปยัง YTDownloader|ส่งลิงก์นี้ไปยัง YTDownloader|กำลังส่ง…|ส่งไปยังแอปเดสก์ท็อป'
}

def main():
    assets = ROOT / 'browser-extension'
    catalog_path = ROOT / 'src/yt_downloader/ui/translations.json'
    catalog_text = catalog_path.read_text('utf-8')
    catalog = json.loads(catalog_text)
    for locale, row in ROWS.items():
        values = row.split('|')
        assert len(values) == len(KEYS), (locale, len(values), len(KEYS))
        desktop_locale = {'en':'en-US','ja':'ja-JP','ko':'ko-KR','ru':'ru-RU','es':'es-ES','pt':'pt-BR','vi':'vi-VN','th':'th-TH'}.get(locale, locale)
        for key, value in zip(KEYS, values):
            item = catalog['messages'].setdefault('browser.' + key, {})
            if locale != desktop_locale: item.pop(locale, None)
            item[desktop_locale] = value
        browser_locale = {'zh-CN':'zh_CN','zh-TW':'zh_TW'}.get(locale,locale)
        folder = assets / 'shared/_locales' / browser_locale
        folder.mkdir(parents=True, exist_ok=True)
        (folder / 'messages.json').write_text(json.dumps({key:dict(message=value) for key,value in zip(KEYS,values)},ensure_ascii=False,indent=2)+'\n','utf-8')
    from browser_onboarding_translations import KEYS as desktop_keys, ROWS as desktop_rows
    for locale, row in desktop_rows.items():
        values = row.split('|')
        assert len(values) == len(desktop_keys), (locale, len(values))
        for key, value in zip(desktop_keys, values):
            catalog['messages'].setdefault('browser.' + key, {})[locale] = value
    from browser_portable_translations import KEYS as portable_keys, ROWS as portable_rows
    for locale, row in portable_rows.items():
        values = row.split('|')
        assert len(values) == len(portable_keys), (locale, len(values))
        for key, value in zip(portable_keys, values):
            catalog['messages'].setdefault('browser.' + key, {})[locale] = value
    # Preserve the established compact catalog and every unrelated translation.
    browser_lines = [f'    {json.dumps(key)}: ' + json.dumps(value, ensure_ascii=False, separators=(',', ':'))
                     for key, value in catalog['messages'].items() if key.startswith('browser.')]
    catalog_text = re.sub(r'^    "browser\.[^"\n]+": .*\n', '', catalog_text, flags=re.MULTILINE)
    closing = catalog_text.rfind('\n  }')
    prefix = catalog_text[:closing].rstrip().rstrip(',')
    catalog_path.write_text(prefix + ',\n' + ',\n'.join(browser_lines) + catalog_text[closing:], 'utf-8')
    identity_path = assets / 'identity.json'
    if identity_path.exists(): identity = json.loads(identity_path.read_text('utf-8'))
    else:
        from cryptography.hazmat.primitives.asymmetric import rsa
        from cryptography.hazmat.primitives import serialization
        identity = {}
        for browser in ('chrome','edge'):
            public = rsa.generate_private_key(public_exponent=65537,key_size=2048).public_key().public_bytes(serialization.Encoding.DER,serialization.PublicFormat.SubjectPublicKeyInfo)
            digest = hashlib.sha256(public).digest()[:16].hex()
            identity[browser] = dict(id=''.join(chr(ord('a')+int(c,16)) for c in digest), key=base64.b64encode(public).decode())
        identity['firefox'] = dict(id='send-to-ytdownloader@kekaodeni.github.io')
        identity_path.write_text(json.dumps(identity,indent=2)+'\n','utf-8')
    (assets / 'manifests').mkdir(exist_ok=True)
    for browser in ('chrome','edge','firefox'):
        manifest = dict(manifest_version=3,name='__MSG_name__',description='__MSG_description__',version='1.0.0',
                        default_locale='en',permissions=['activeTab','contextMenus','nativeMessaging'],
                        action=dict(default_popup='popup.html',default_title='__MSG_send__',default_icon={'16':'icons/icon16.png','32':'icons/icon32.png'}),
                        icons={str(n):f'icons/icon{n}.png' for n in (16,32,48,128)})
        if browser == 'firefox':
            manifest['background'] = dict(scripts=['core.js','background.js'])
            manifest['browser_specific_settings'] = dict(gecko=dict(id=identity[browser]['id'],strict_min_version='140.0',data_collection_permissions=dict(required=['none'])))
        else:
            manifest['background'] = dict(service_worker='background.js')
            manifest['key'] = identity[browser]['key']
        (assets / 'manifests' / (browser+'.json')).write_text(json.dumps(manifest,indent=2)+'\n','utf-8')
    from PIL import Image
    (assets / 'shared/icons').mkdir(exist_ok=True)
    for size in (16,32,48,128):
        with Image.open(ROOT / 'assets/app.ico') as icon:
            icon.convert('RGBA').resize((size,size),Image.Resampling.LANCZOS).save(assets / f'shared/icons/icon{size}.png')

if __name__ == '__main__': main()
